### ISSUE TITLE
Unable to create the requested editor

### ISSUE THREAD

**Issue by inSaneWolf666** [CGJennings/strange-eons#72]
Can't open/create Location or Gate cards for Arkham Horror in Version: 3.3 (4416α). The following message appears:

'unable to create the requested editor
invalid hotSpot
Index Out Of Bounds Exception'

It still works in Version: 3.3.4241, didn't check all other possible components.

This is an amazing piece of software you made available, thank you very much

**Comment by CGJennings** [comment]
Thanks.

Have you updated the Arkham Horror plug-in to the latest version? (**Toolbox/Catalogue**). If you don't see the latest version, an old catalogue may be cached; press Enter in the catalog URL field to reload it.

I see that the listed version, though updated, shows as 2021, so it is possible that the date wasn't updated. (It should be updated anyway, just for clarity.)

**Comment by inSaneWolf666** [comment]
Hi,
from 'report a bug' inside StrangeEons:
Bug: Strange Eons 4416
Platform: FreeBSD (v13.2-STABLE-amd64-4 CPUs)
JRE: 11.0.21 OpenJDK BSD Porting Team

I deleted my .StrangeEons3 directory to force a redownload
My Arkham Horror version is now Wed Nov 24 2021, it says 'installed and up to date', press Enter in the catalog URL field to reload it doesn't change it.

**Comment by CGJennings** [comment]
I suspect that the problem has to do with the custom cursor used by the colour selector, based on the "hot spot" text.

Do you know if your desktop is scaled (for a high DPI/"Retina" type display, for example, a 4k monitor)?

If you know how, can you start the app from a shell so that you can see the full stack trace of the error? (It should be logged to stdout/stderr).

**Comment by inSaneWolf666** [comment]
I start Strange Eons from command line, this is output of opening and trying to create new Location Card:

christoph@christoph-ghostbsd-pc /u/h/c/StrangeEons3.4> java -Xmx2g -javaagent:strange-eons.jar -cp strange-eons.jar strangeeons
[Feb 4, 2024 4:37:48 PM] ca.cgjennings.apps.arkham.StrangeEons applyGraphicsOptions
  INFO: renderer selection matrix: Software=true, Direct3D=false, Metal=false, OpenGL=false, XRender=true
[Feb 4, 2024 4:37:48 PM] ca.cgjennings.apps.arkham.StrangeEons applyTextAntialiasingOptions
  INFO: set text antialiasing mode to lcd
[Feb 4, 2024 4:38:07 PM] ca.cgjennings.apps.arkham.dialog.ErrorDialog displayError
  WARNING: Unable to create the requested editor
java.lang.IndexOutOfBoundsException: invalid hotSpot
	at java.desktop/sun.awt.CustomCursor.<init>(Unknown Source)
	at java.desktop/sun.awt.X11CustomCursor.<init>(Unknown Source)
	at java.desktop/sun.awt.X11.XCustomCursor.<init>(Unknown Source)
	at java.desktop/sun.awt.X11.XToolkit.createCustomCursor(Unknown Source)
	at resources.ResourceKit.createCustomCursor(ResourceKit.java:2611)
	at ca.cgjennings.ui.EyeDropper.initialize(EyeDropper.java:204)
	at ca.cgjennings.ui.EyeDropper.<init>(EyeDropper.java:53)
	at ca.cgjennings.apps.arkham.HSBPanel.initComponents(HSBPanel.java:330)
	at ca.cgjennings.apps.arkham.HSBPanel.<init>(HSBPanel.java:63)
	at ca.cgjennings.apps.arkham.ArkhamEncounterEditor.initComponents(ArkhamEncounterEditor.java:200)
	at ca.cgjennings.apps.arkham.ArkhamEncounterEditor.<init>(ArkhamEncounterEditor.java:38)
	at ca.cgjennings.apps.arkham.component.ArkhamEncounter.createDefaultEditor(ArkhamEncounter.java:91)
	at gamedata.ClassMap$Entry.createClassBasedItem(ClassMap.java:550)
	at gamedata.ClassMap$Entry.createEditor(ClassMap.java:474)
	at ca.cgjennings.apps.arkham.NewEditorDialog$ComponentListItem.createEditor(NewEditorDialog.java:792)
	at ca.cgjennings.apps.arkham.NewEditorDialog.createSelectedComponent(NewEditorDialog.java:657)
	at ca.cgjennings.apps.arkham.NewEditorDialog.componentListMouseClicked(NewEditorDialog.java:580)
	at ca.cgjennings.apps.arkham.NewEditorDialog$2.mouseClicked(NewEditorDialog.java:454)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by CGJennings** [comment]
Thanks, this confirms what I suspected. I should have a fix shortly.

**Comment by CGJennings** [comment]
Should be fixed by #74, but feel free to reopen if not. Thanks again for reporting this.
